theme: jekyll-theme-cayman
title: Chris Thinks

layout: page
title: "Implementation One: Bayesian Methods for Media Mix Modeling with Carryover and Shape Effects"
permalink: /mmm_carryover_and_shape_effects/
